version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: blog-nginx
    ports:
      - "80:80"
    volumes:
      - ./src/backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - frontend

  php:
    build: ./docker/php
    container_name: blog-php
    volumes:
      - ./src/backend:/var/www/html
    working_dir: /var/www/html
    environment:
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1

  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: bloguser
      MYSQL_PASSWORD: blogpass
    volumes:
      - mysql-data:/var/lib/mysql

  frontend:
    build: ./docker/node
    container_name: blog-frontend
    working_dir: /app
    volumes:
      - ./src/frontend:/app
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mysql-data:
